# @package _group_
defaults:
    - architecture: smaller
    - dataset: cifar100
    - experiment: training/cifar
    - optimizer: simclr
    - loss: simclr
    - distributed: base
    - hydra/output: custom

parameter:
    algorithm: self_supervised
    d: 128 # dimensionality of feature representation
